#!/bin/zsh

source ~/.scripts/.display/.names

xrandr --output $M_HDMI --off
xrandr --output $M_DL_LEFT --off
xrandr --output $M_DL_RIGHT --off

xrandr --output $M_LAPTOP --mode 1920x1080 --pos 0x0

sh ~/.scripts/compton_restart
zsh ~/.scripts/.display/.set_bg.sh

echo "$0" > ~/.scripts/.display/.last
