#!/bin/zsh

source ~/.scripts/.display/.names

xrandr --output $M_DL_LEFT --off
xrandr --output $M_DL_RIGHT --off

xrandr --output $M_LAPTOP --mode 1920x1080 --pos 0x0
xrandr --output $M_HDMI --mode 1920x1080 --same-as $M_LAPTOP

sh ~/.scripts/compton_restart
zsh ~/.scripts/feh_bg -s -t
