#!/bin/zsh

# load
BR=$(~/.scripts/.utils/parsepercent $1)
FRAC=$(($BR / 100.0))
source ~/.scripts/.display/.names

# get max hardware backlight value
HW_MAX=$(brightnessctl --device=intel_backlight m)

# get hw brightness value
zmodload zsh/mathfunc
integer HW_BR=$(( rint($FRAC * $HW_MAX) ))

# if we can use laptop display backlight
if [[ $BR -ge 0 && $BR -le 100 ]]; then
	# set xrandr to 100%
	xrandr --output $M0 --brightness 1
	# use hardware
	brightnessctl --device=intel_backlight set $HW_BR
else
	# set hardware to 100%
	echo $HW_MAX > /sys/class/backlight/intel_backlight/brightness
	# use xrandr
	xrandr --output $M0 --brightness $FRAC
fi

# external monitors (always using xrandr)
xrandr --output $M1 --brightness $FRAC
xrandr --output $M2 --brightness $FRAC

# notify
dunstify -u 0 -t 1500 "Brightness $BR%"
