#!/bin/zsh


zmodload zsh/mathfunc

# define some constants
HW_LOWEST=140;		KEY_LOWEST='lowest'
HW_LOW=400;			KEY_LOW='low'
HW_MEDIUM=1500;		KEY_MEDIUM='medium'
HW_HIGH=12000;		KEY_HIGH='high'
HW_MAX=24000;		KEY_MAX='max'

# output constants
if [[ $1 == 'keys' ]]; then
	echo "$KEY_LOWEST\n$KEY_LOW\n$KEY_MEDIUM\n$KEY_HIGH\n$KEY_MAX"
	exit 0
fi

# load hardware
source ~/.scripts/.display/.names

# get requested value
if [[ $1 == $KEY_LOWEST ]]; then
	HW_REQ=$HW_LOWEST
elif [[ $1 == $KEY_LOW ]]; then
	HW_REQ=$HW_LOW
elif [[ $1 == $KEY_MEDIUM ]]; then
	HW_REQ=$HW_MEDIUM
elif [[ $1 == $KEY_HIGH ]]; then
	HW_REQ=$HW_HIGH
elif [[ $1 == $KEY_MAX ]]; then
	HW_REQ=$HW_MAX
fi

# get brightness percentage
if [[ $HW_REQ ]]; then		# calculate from special value
	HW_BR=$HW_REQ
	FRAC=$(( $HW_REQ / 24000.0 ))
	integer BR=$(( rint( $FRAC * 100 ) ))
else						# parse from input
	BR=$(~/.scripts/.utils/parsepercent $1)
	FRAC=$(($BR / 100.0))
	integer HW_BR=$(( rint($FRAC * $HW_MAX) ))
fi

# if we can use laptop display backlight
if [[ $BR -ge 0 && $BR -le 100 ]]; then
	# set xrandr to 100%
	xrandr --output $M0 --brightness 1
	# use hardware
	brightnessctl --device=intel_backlight set $HW_BR
else
	# set hardware to 100%
	brightnessctl --device=intel_backlight set $HW_MAX
	# use xrandr
	xrandr --output $M0 --brightness $FRAC
fi

# external monitors (always using xrandr)
FRAC_EXT=$(( $FRAC ** 0.25 ))
xrandr --output $M1 --brightness $FRAC_EXT
xrandr --output $M2 --brightness $FRAC_EXT

# notify
if [[ $HW_REQ ]]; then
	NOTIFY=$HW_REQ
else
	NOTIFY=$BR%
fi
dunstify -u 0 -t 1500 "Brightness $NOTIFY"
