#!/bin/zsh

STEPS=20

VAL=$1
test $2 && OFF_TEXT=$2 || OFF_TEXT='off'
OT_LEN=$(printf "%s" "$OFF_TEXT" | wc -m)

ACTIVE=$(( $VAL / (100/$STEPS) ))
INACTIVE=$(( $STEPS - $ACTIVE ))

draw() {
	COUNT=$1
	SYMBOL=$2

	seq -s $SYMBOL 0 $COUNT | sed 's/[0-9]//g'
}

test $VAL -ne 0 \
	&& echo $(draw $ACTIVE "─")$(draw $INACTIVE "·") \
	|| echo $(draw $(( ($STEPS - $OT_LEN) / 2 )) "·")$OFF_TEXT$(draw $(( ($STEPS - $OT_LEN + 1) / 2 )) "·")
